#!/bin/bash

set -e

LICENSE_DATA=$1
ARCHIVE_USER=$2
ARCHIVE_PW=$3
STARDOG_RELEASE_URL=$4
STARDOG_VERSION=$5
GRAV_REPO_DIR=$6
LINUX_STAGE=$7
OUTPUT_DIR=$8

THIS_DIR=$(pwd)

ls $GRAV_REPO_DIR/ci
RELEASE_FILE=$THIS_DIR/$ENV_INPUT_DIR/stardog-$STARDOG_VERSION.zip
LICENSE_FILE=$THIS_DIR/$ENV_INPUT_DIR/stardog-license-key.bin

sed -e "s^@@LICENSE@@^$LICENSE_FILE^" -e "s^@@RELEASE@@^$RELEASE_FILE^" -e "s^@@VERSION@@^$STARDOG_VERSION^" $GRAV_REPO_DIR/ci/default.json.template > $OUTPUT_DIR/default.json

echo $LICENSE_DATA | base64 -d > $OUTPUT_DIR/stardog-license-key.bin
curl -u $ARCHIVE_USER:$ARCHIVE_PW -o $OUTPUT_DIR/stardog-$STARDOG_VERSION.zip $STARDOG_RELEASE_URL

ls $LINUX_STAGE
cp -r $LINUX_STAGE/* $OUTPUT_DIR
